import type { MealSeed } from '@/types/recipe';

/**
 * Starter meal database — a realistic, non-exhaustive set of common meals so
 * new users have something to work with before adding their own. Add more
 * entries the same way; there's nothing generated or computed here.
 */
export const MEAL_SEED: MealSeed[] = [
  // ---------- Breakfast ----------
  { id: 'oatmeal', name: 'Oatmeal', mealType: ['breakfast'], categories: ['vegan', 'vegetarian', 'healthy', 'quick', 'budget', 'low-effort'], ingredients: ['Oats', 'Almond Milk', 'Banana'], effort: 'low', time: 5, servings: 1, nutrition: { kcal: 260, proteinGrams: 7, carbohydrateGrams: 47, fatGrams: 5, saturatedFatGrams: 1, fiberGrams: 6, sugarGrams: 14, sodiumMilligrams: 90, source: 'estimated', completeness: 'complete' } },
  { id: 'overnight-oats', name: 'Overnight Oats', mealType: ['breakfast'], categories: ['vegan', 'vegetarian', 'healthy', 'meal-prep', 'budget', 'cold', 'low-effort'], ingredients: ['Oats', 'Oat Milk', 'Chia Seeds', 'Banana'], effort: 'low', time: 5 },
  { id: 'yogurt-bowl', name: 'Yogurt Bowl', mealType: ['breakfast', 'snack'], categories: ['vegetarian', 'healthy', 'quick', 'sweet'], ingredients: ['Yogurt', 'Granola', 'Banana', 'Honey'], effort: 'low', time: 5 },
  { id: 'granola-bowl', name: 'Granola Bowl', mealType: ['breakfast', 'snack'], categories: ['vegetarian', 'quick', 'sweet', 'budget', 'low-effort'], ingredients: ['Granola', 'Milk'], effort: 'low', time: 3 },
  { id: 'cereal', name: 'Cereal', mealType: ['breakfast'], categories: ['vegetarian', 'quick', 'sweet', 'budget', 'low-effort'], ingredients: ['Cornflakes', 'Milk'], effort: 'low', time: 3 },
  { id: 'pancakes', name: 'Pancakes', mealType: ['breakfast'], categories: ['vegetarian', 'comfort', 'sweet'], ingredients: ['Pancake Mix', 'Eggs', 'Milk', 'Butter'], effort: 'medium', time: 20 },
  { id: 'protein-pancakes', name: 'Protein Pancakes', mealType: ['breakfast'], categories: ['vegetarian', 'high-protein', 'healthy'], ingredients: ['Eggs', 'Oats', 'Banana', 'Cottage Cheese'], effort: 'medium', time: 20 },
  { id: 'french-toast', name: 'French Toast', mealType: ['breakfast'], categories: ['vegetarian', 'comfort', 'sweet'], ingredients: ['Bread', 'Eggs', 'Milk', 'Butter'], effort: 'medium', time: 15 },
  { id: 'toast', name: 'Toast', mealType: ['breakfast', 'snack'], categories: ['vegetarian', 'quick', 'budget', 'low-effort'], ingredients: ['Bread', 'Butter'], effort: 'low', time: 3 },
  { id: 'peanut-butter-toast', name: 'Peanut Butter Toast', mealType: ['breakfast', 'snack'], categories: ['vegan', 'vegetarian', 'quick', 'budget', 'sweet', 'low-effort'], ingredients: ['Bread', 'Peanut Butter'], effort: 'low', time: 3 },
  { id: 'avocado-toast', name: 'Avocado Toast', mealType: ['breakfast', 'lunch'], categories: ['vegan', 'vegetarian', 'healthy', 'quick'], ingredients: ['Bread', 'Avocado', 'Lemon', 'Salt'], effort: 'low', time: 8 },
  { id: 'bagel', name: 'Bagel', mealType: ['breakfast'], categories: ['vegetarian', 'quick', 'budget'], ingredients: ['Bagels', 'Cottage Cheese', 'Cucumber'], effort: 'low', time: 5 },
  { id: 'smoothie', name: 'Smoothie', mealType: ['breakfast', 'drink'], categories: ['vegan', 'vegetarian', 'healthy', 'quick', 'cold'], ingredients: ['Banana', 'Strawberry', 'Almond Milk'], effort: 'low', time: 5 },
  { id: 'fruit-bowl', name: 'Fruit Bowl', mealType: ['breakfast', 'snack', 'dessert'], categories: ['vegan', 'vegetarian', 'healthy', 'quick', 'cold', 'budget', 'low-effort'], ingredients: ['Banana', 'Apple', 'Grapes'], effort: 'low', time: 5 },
  { id: 'scrambled-eggs', name: 'Scrambled Eggs', mealType: ['breakfast'], categories: ['vegetarian', 'high-protein', 'quick', 'savory', 'hot'], ingredients: ['Eggs', 'Butter', 'Salt'], effort: 'low', time: 8 },
  { id: 'fried-eggs', name: 'Fried Eggs', mealType: ['breakfast'], categories: ['vegetarian', 'high-protein', 'quick', 'savory', 'hot', 'low-effort'], ingredients: ['Eggs', 'Butter'], effort: 'low', time: 6 },
  { id: 'boiled-eggs', name: 'Boiled Eggs', mealType: ['breakfast', 'snack'], categories: ['vegetarian', 'high-protein', 'quick', 'budget', 'low-effort'], ingredients: ['Eggs'], effort: 'low', time: 10 },
  { id: 'breakfast-burrito', name: 'Breakfast Burrito', mealType: ['breakfast'], categories: ['high-protein', 'comfort', 'savory', 'hot'], ingredients: ['Tortillas', 'Eggs', 'Cheese', 'Bell Pepper'], effort: 'medium', time: 15 },
  { id: 'muesli-bowl', name: 'Muesli Bowl', mealType: ['breakfast'], categories: ['vegetarian', 'healthy', 'quick', 'cold'], ingredients: ['Muesli', 'Milk', 'Apple'], effort: 'low', time: 5 },
  { id: 'chia-pudding', name: 'Chia Pudding', mealType: ['breakfast', 'dessert'], categories: ['vegan', 'vegetarian', 'healthy', 'meal-prep', 'cold'], ingredients: ['Chia Seeds', 'Oat Milk', 'Mango'], effort: 'low', time: 5 },
  { id: 'waffles', name: 'Waffles', mealType: ['breakfast'], categories: ['vegetarian', 'comfort', 'sweet'], ingredients: ['Pancake Mix', 'Eggs', 'Milk'], effort: 'medium', time: 20 },
  { id: 'egg-sandwich', name: 'Egg Sandwich', mealType: ['breakfast', 'lunch'], categories: ['vegetarian', 'high-protein', 'quick', 'savory'], ingredients: ['Bread', 'Eggs', 'Mayonnaise'], effort: 'low', time: 10 },

  // ---------- Lunch ----------
  { id: 'sandwich', name: 'Sandwich', mealType: ['lunch'], categories: ['quick', 'savory', 'budget'], ingredients: ['Bread', 'Cheese', 'Lettuce', 'Tomato'], effort: 'low', time: 8 },
  { id: 'grilled-cheese', name: 'Grilled Cheese', mealType: ['lunch'], categories: ['vegetarian', 'comfort', 'savory', 'quick', 'budget'], ingredients: ['Bread', 'Cheese', 'Butter'], effort: 'low', time: 10, servings: 1, nutrition: { kcal: 350, proteinGrams: 13, carbohydrateGrams: 28, fatGrams: 20, saturatedFatGrams: 11, fiberGrams: 1, sugarGrams: 3, sodiumMilligrams: 680, source: 'estimated', completeness: 'complete' } },
  { id: 'tosti', name: 'Tosti', mealType: ['lunch', 'snack'], categories: ['vegetarian', 'comfort', 'savory', 'quick', 'budget', 'low-effort'], ingredients: ['Bread', 'Cheese'], effort: 'low', time: 8 },
  { id: 'wrap', name: 'Wrap', mealType: ['lunch'], categories: ['quick', 'savory'], ingredients: ['Wraps', 'Chicken', 'Lettuce', 'Tomato'], effort: 'low', time: 10 },
  { id: 'caesar-salad', name: 'Caesar Salad', mealType: ['lunch'], categories: ['savory', 'healthy'], ingredients: ['Lettuce', 'Chicken', 'Parmesan'], effort: 'medium', time: 15 },
  { id: 'falafel-wrap', name: 'Falafel Wrap', mealType: ['lunch'], categories: ['vegan', 'vegetarian', 'healthy', 'savory'], ingredients: ['Wraps', 'Falafel', 'Lettuce', 'Tomato'], effort: 'medium', time: 15, servings: 1, nutrition: { kcal: 380, proteinGrams: 13, carbohydrateGrams: 48, fatGrams: 15, saturatedFatGrams: 2, fiberGrams: 8, sugarGrams: 4, sodiumMilligrams: 620, source: 'estimated', completeness: 'complete' } },
  { id: 'burrito', name: 'Burrito', mealType: ['lunch', 'dinner'], categories: ['savory', 'comfort'], ingredients: ['Tortillas', 'Beef', 'White Rice', 'Cheese'], effort: 'medium', time: 20 },
  { id: 'burrito-bowl', name: 'Burrito Bowl', mealType: ['lunch', 'dinner'], categories: ['high-protein', 'healthy', 'meal-prep'], ingredients: ['White Rice', 'Chicken', 'Corn', 'Bell Pepper'], effort: 'medium', time: 20 },
  { id: 'poke-bowl', name: 'Poké Bowl', mealType: ['lunch', 'dinner'], categories: ['pescatarian', 'healthy', 'high-protein'], ingredients: ['Sushi Rice', 'Salmon', 'Avocado', 'Cucumber'], effort: 'medium', time: 20 },
  { id: 'soup', name: 'Soup', mealType: ['lunch', 'dinner'], categories: ['comfort', 'hot', 'healthy', 'budget'], ingredients: ['Carrot', 'Onion', 'Garlic'], effort: 'medium', time: 25 },
  { id: 'tomato-soup', name: 'Tomato Soup', mealType: ['lunch', 'dinner'], categories: ['vegan', 'vegetarian', 'comfort', 'hot', 'budget'], ingredients: ['Tomato Sauce', 'Onion', 'Garlic'], effort: 'low', time: 20 },
  { id: 'pasta-salad', name: 'Pasta Salad', mealType: ['lunch'], categories: ['vegetarian', 'cold', 'meal-prep'], ingredients: ['Pasta', 'Tomato', 'Cucumber', 'Mozzarella'], effort: 'low', time: 15 },
  { id: 'chicken-salad', name: 'Chicken Salad', mealType: ['lunch'], categories: ['high-protein', 'healthy', 'cold'], ingredients: ['Chicken', 'Lettuce', 'Tomato', 'Cucumber'], effort: 'low', time: 12 },
  { id: 'greek-salad', name: 'Greek Salad', mealType: ['lunch'], categories: ['vegetarian', 'healthy', 'cold', 'savory'], ingredients: ['Tomato', 'Cucumber', 'Feta'], effort: 'low', time: 10 },
  { id: 'hummus-wrap', name: 'Hummus Wrap', mealType: ['lunch'], categories: ['vegan', 'vegetarian', 'healthy', 'quick'], ingredients: ['Wraps', 'Hummus', 'Cucumber', 'Spinach'], effort: 'low', time: 8 },
  { id: 'quesadilla', name: 'Quesadilla', mealType: ['lunch', 'dinner'], categories: ['vegetarian', 'comfort', 'savory', 'quick'], ingredients: ['Tortillas', 'Cheese', 'Bell Pepper'], effort: 'low', time: 12 },
  { id: 'club-sandwich', name: 'Club Sandwich', mealType: ['lunch'], categories: ['high-protein', 'savory'], ingredients: ['Bread', 'Chicken', 'Lettuce', 'Tomato'], effort: 'medium', time: 15 },
  { id: 'tuna-sandwich', name: 'Tuna Sandwich', mealType: ['lunch'], categories: ['pescatarian', 'high-protein', 'quick'], ingredients: ['Bread', 'Tuna', 'Mayonnaise', 'Lettuce'], effort: 'low', time: 8 },
  { id: 'egg-salad-sandwich', name: 'Egg Salad Sandwich', mealType: ['lunch'], categories: ['vegetarian', 'high-protein', 'quick'], ingredients: ['Bread', 'Eggs', 'Mayonnaise'], effort: 'low', time: 10 },
  { id: 'noodle-soup', name: 'Noodle Soup', mealType: ['lunch', 'dinner'], categories: ['comfort', 'hot', 'savory'], ingredients: ['Noodles', 'Chicken', 'Carrot', 'Soy Sauce'], effort: 'medium', time: 20 },

  // ---------- Dinner ----------
  { id: 'spaghetti-bolognese', name: 'Spaghetti Bolognese', mealType: ['dinner'], categories: ['comfort', 'savory', 'meal-prep'], ingredients: ['Spaghetti', 'Beef', 'Tomato Sauce', 'Onion', 'Garlic'], effort: 'medium', time: 35 },
  { id: 'carbonara', name: 'Carbonara', mealType: ['dinner'], categories: ['comfort', 'savory'], ingredients: ['Spaghetti', 'Eggs', 'Parmesan'], effort: 'medium', time: 25 },
  { id: 'lasagna', name: 'Lasagna', mealType: ['dinner'], categories: ['comfort', 'savory', 'meal-prep'], ingredients: ['Pasta', 'Beef', 'Tomato Sauce', 'Cheese'], effort: 'high', time: 60 },
  { id: 'stir-fry', name: 'Stir Fry', mealType: ['dinner'], categories: ['healthy', 'quick', 'savory'], ingredients: ['Chicken', 'Mixed Vegetables', 'Soy Sauce', 'White Rice'], effort: 'medium', time: 20 },
  { id: 'fried-rice', name: 'Fried Rice', mealType: ['dinner', 'lunch'], categories: ['savory', 'quick', 'budget', 'meal-prep'], ingredients: ['White Rice', 'Eggs', 'Peas', 'Soy Sauce'], effort: 'low', time: 15 },
  { id: 'vegetable-curry', name: 'Vegetable Curry', mealType: ['dinner'], categories: ['vegan', 'vegetarian', 'healthy', 'comfort', 'hot'], ingredients: ['Curry Powder', 'Sweet Potato', 'Spinach', 'White Rice'], effort: 'medium', time: 30 },
  { id: 'chicken-curry', name: 'Chicken Curry', mealType: ['dinner'], categories: ['comfort', 'savory', 'hot'], ingredients: ['Chicken', 'Curry Powder', 'White Rice', 'Onion'], effort: 'medium', time: 30, servings: 2, nutrition: { kcal: 420, proteinGrams: 32, carbohydrateGrams: 30, fatGrams: 18, saturatedFatGrams: 4, fiberGrams: 3, sugarGrams: 5, sodiumMilligrams: 540, source: 'estimated', completeness: 'complete' } },
  { id: 'chili', name: 'Chili', mealType: ['dinner'], categories: ['comfort', 'savory', 'hot', 'meal-prep', 'budget'], ingredients: ['Beef', 'Tomato Sauce', 'Onion'], effort: 'medium', time: 35 },
  { id: 'pizza', name: 'Pizza', mealType: ['dinner'], categories: ['comfort', 'savory'], ingredients: ['Pizza', 'Cheese'], effort: 'low', time: 15 },
  { id: 'burger', name: 'Burger', mealType: ['dinner'], categories: ['comfort', 'savory'], ingredients: ['Burger Buns', 'Beef', 'Cheese', 'Lettuce'], effort: 'medium', time: 20 },
  { id: 'beyond-burger', name: 'Beyond Burger', mealType: ['dinner'], categories: ['vegan', 'vegetarian', 'high-protein', 'comfort'], ingredients: ['Burger Buns', 'Beyond Burger', 'Lettuce', 'Tomato'], effort: 'low', time: 15 },
  { id: 'vegan-burger', name: 'Vegan Burger', mealType: ['dinner'], categories: ['vegan', 'vegetarian', 'comfort'], ingredients: ['Burger Buns', 'Vegan Burger', 'Lettuce'], effort: 'low', time: 15 },
  { id: 'vegan-chicken-burger', name: 'Vegan Chicken Burger', mealType: ['dinner'], categories: ['vegan', 'vegetarian', 'comfort'], ingredients: ['Burger Buns', 'Vegan Chicken', 'Lettuce'], effort: 'low', time: 15 },
  { id: 'falafel-bowl', name: 'Falafel Bowl', mealType: ['dinner', 'lunch'], categories: ['vegan', 'vegetarian', 'healthy', 'high-protein'], ingredients: ['Falafel', 'White Rice', 'Cucumber', 'Tomato'], effort: 'medium', time: 20 },
  { id: 'tofu-stir-fry', name: 'Tofu Stir Fry', mealType: ['dinner'], categories: ['vegan', 'vegetarian', 'healthy', 'high-protein', 'quick'], ingredients: ['Tofu', 'Mixed Vegetables', 'Soy Sauce', 'White Rice'], effort: 'medium', time: 20 },
  { id: 'mac-and-cheese', name: 'Mac & Cheese', mealType: ['dinner'], categories: ['vegetarian', 'comfort', 'savory'], ingredients: ['Pasta', 'Cheese', 'Milk', 'Butter'], effort: 'low', time: 20 },
  { id: 'loaded-fries', name: 'Loaded Fries', mealType: ['dinner', 'snack'], categories: ['vegetarian', 'comfort', 'savory'], ingredients: ['Fries', 'Cheese'], effort: 'low', time: 20 },
  { id: 'gyoza-plate', name: 'Gyoza Plate', mealType: ['dinner'], categories: ['vegetarian', 'savory', 'quick', 'comfort'], ingredients: ['Gyoza', 'Soy Sauce'], effort: 'low', time: 12 },
  { id: 'roast-chicken', name: 'Roast Chicken', mealType: ['dinner'], categories: ['high-protein', 'comfort', 'meal-prep'], ingredients: ['Chicken', 'Potato', 'Carrot'], effort: 'high', time: 70 },
  { id: 'grilled-chicken', name: 'Grilled Chicken', mealType: ['dinner'], categories: ['high-protein', 'healthy', 'quick'], ingredients: ['Chicken', 'Lemon', 'Olive Oil'], effort: 'medium', time: 20 },
  { id: 'baked-salmon', name: 'Baked Salmon', mealType: ['dinner'], categories: ['pescatarian', 'healthy', 'high-protein'], ingredients: ['Salmon', 'Lemon', 'Broccoli'], effort: 'medium', time: 25 },
  { id: 'fish-and-chips', name: 'Fish and Chips', mealType: ['dinner'], categories: ['pescatarian', 'comfort', 'savory'], ingredients: ['Salmon', 'Fries'], effort: 'medium', time: 25 },
  { id: 'shepherds-pie', name: "Shepherd's Pie", mealType: ['dinner'], categories: ['comfort', 'savory', 'meal-prep'], ingredients: ['Beef', 'Potato', 'Peas', 'Carrot'], effort: 'high', time: 50 },
  { id: 'chana-masala', name: 'Chana Masala', mealType: ['dinner'], categories: ['vegan', 'vegetarian', 'healthy', 'comfort', 'hot', 'budget'], ingredients: ['Curry Powder', 'Tomato Sauce', 'White Rice'], effort: 'medium', time: 25 },
  { id: 'tacos', name: 'Tacos', mealType: ['dinner'], categories: ['savory', 'quick'], ingredients: ['Tortillas', 'Beef', 'Lettuce', 'Cheese'], effort: 'low', time: 20 },
  { id: 'fajitas', name: 'Fajitas', mealType: ['dinner'], categories: ['savory', 'healthy'], ingredients: ['Tortillas', 'Chicken', 'Bell Pepper', 'Onion'], effort: 'medium', time: 25 },
  { id: 'ramen', name: 'Ramen', mealType: ['dinner'], categories: ['comfort', 'savory', 'hot'], ingredients: ['Noodles', 'Eggs', 'Soy Sauce', 'Mixed Vegetables'], effort: 'medium', time: 20 },
  { id: 'pad-thai', name: 'Pad Thai', mealType: ['dinner'], categories: ['savory', 'quick'], ingredients: ['Noodles', 'Eggs', 'Bell Pepper', 'Soy Sauce'], effort: 'medium', time: 20 },
  { id: 'sushi-rolls', name: 'Sushi Rolls', mealType: ['dinner', 'lunch'], categories: ['pescatarian', 'healthy'], ingredients: ['Sushi Rice', 'Salmon', 'Avocado', 'Cucumber'], effort: 'high', time: 40 },
  { id: 'risotto', name: 'Risotto', mealType: ['dinner'], categories: ['vegetarian', 'comfort'], ingredients: ['White Rice', 'Parmesan', 'Mushroom', 'Onion'], effort: 'high', time: 35 },
  { id: 'meatballs-pasta', name: 'Meatballs & Pasta', mealType: ['dinner'], categories: ['comfort', 'savory'], ingredients: ['Spaghetti', 'Beef', 'Tomato Sauce'], effort: 'medium', time: 30 },
  { id: 'bbq-chicken', name: 'BBQ Chicken', mealType: ['dinner'], categories: ['savory', 'high-protein'], ingredients: ['Chicken', 'BBQ Sauce', 'Potato'], effort: 'medium', time: 30 },
  { id: 'shakshuka', name: 'Shakshuka', mealType: ['dinner', 'breakfast'], categories: ['vegetarian', 'comfort', 'savory', 'hot'], ingredients: ['Eggs', 'Tomato Sauce', 'Bell Pepper', 'Onion'], effort: 'medium', time: 25 },

  // ---------- Snacks ----------
  { id: 'banana', name: 'Banana', mealType: ['snack'], categories: ['vegan', 'vegetarian', 'healthy', 'quick', 'budget', 'low-effort'], ingredients: ['Banana'], effort: 'low', time: 1 },
  { id: 'apple', name: 'Apple', mealType: ['snack'], categories: ['vegan', 'vegetarian', 'healthy', 'quick', 'budget', 'low-effort'], ingredients: ['Apple'], effort: 'low', time: 1 },
  { id: 'grapes', name: 'Grapes', mealType: ['snack'], categories: ['vegan', 'vegetarian', 'healthy', 'quick', 'cold', 'budget', 'low-effort'], ingredients: ['Grapes'], effort: 'low', time: 1 },
  { id: 'mixed-nuts', name: 'Mixed Nuts', mealType: ['snack'], categories: ['vegan', 'vegetarian', 'healthy', 'high-protein', 'quick', 'budget', 'low-effort'], ingredients: ['Almonds', 'Cashews', 'Walnuts'], effort: 'low', time: 1 },
  { id: 'protein-bar', name: 'Protein Bar', mealType: ['snack'], categories: ['high-protein', 'quick', 'budget', 'low-effort'], ingredients: ['Protein Bar'], effort: 'low', time: 1 },
  { id: 'popcorn', name: 'Popcorn', mealType: ['snack'], categories: ['vegan', 'vegetarian', 'quick', 'budget', 'low-effort'], ingredients: ['Popcorn'], effort: 'low', time: 5 },
  { id: 'rice-cakes', name: 'Rice Cakes', mealType: ['snack'], categories: ['vegan', 'vegetarian', 'healthy', 'quick', 'budget', 'low-effort'], ingredients: ['Rice Cakes', 'Peanut Butter'], effort: 'low', time: 2 },
  { id: 'crackers', name: 'Crackers', mealType: ['snack'], categories: ['vegetarian', 'quick', 'budget', 'low-effort'], ingredients: ['Crackers', 'Cheese'], effort: 'low', time: 3 },
  { id: 'yogurt', name: 'Yogurt', mealType: ['snack'], categories: ['vegetarian', 'healthy', 'quick', 'cold', 'low-effort'], ingredients: ['Yogurt'], effort: 'low', time: 1 },
  { id: 'granola', name: 'Granola', mealType: ['snack'], categories: ['vegetarian', 'quick', 'budget', 'low-effort'], ingredients: ['Granola', 'Yogurt'], effort: 'low', time: 2 },
  { id: 'protein-shake', name: 'Protein Shake', mealType: ['snack', 'drink'], categories: ['vegetarian', 'high-protein', 'quick', 'cold', 'low-effort'], ingredients: ['Protein Shake', 'Milk'], effort: 'low', time: 3, servings: 1, nutrition: { kcal: 160, proteinGrams: 25, carbohydrateGrams: 6, fatGrams: 3, saturatedFatGrams: 1, fiberGrams: 0, sugarGrams: 4, sodiumMilligrams: 130, source: 'estimated', completeness: 'complete' } },
  { id: 'trail-mix', name: 'Trail Mix', mealType: ['snack'], categories: ['vegan', 'vegetarian', 'healthy', 'quick', 'budget', 'low-effort'], ingredients: ['Almonds', 'Cashews', 'Dark Chocolate'], effort: 'low', time: 2 },
  { id: 'hummus-veggies', name: 'Hummus & Veggies', mealType: ['snack'], categories: ['vegan', 'vegetarian', 'healthy', 'quick'], ingredients: ['Hummus', 'Carrot', 'Cucumber'], effort: 'low', time: 5 },
  { id: 'cottage-cheese-bowl', name: 'Cottage Cheese Bowl', mealType: ['snack'], categories: ['vegetarian', 'high-protein', 'healthy', 'quick', 'cold', 'low-effort'], ingredients: ['Cottage Cheese', 'Pineapple'], effort: 'low', time: 3 },
  { id: 'dark-chocolate', name: 'Dark Chocolate', mealType: ['snack', 'dessert'], categories: ['vegetarian', 'sweet', 'quick', 'low-effort'], ingredients: ['Dark Chocolate'], effort: 'low', time: 1 },
  { id: 'edamame', name: 'Edamame', mealType: ['snack'], categories: ['vegan', 'vegetarian', 'healthy', 'high-protein', 'quick', 'low-effort'], ingredients: ['Edamame'], effort: 'low', time: 8 },
  { id: 'pretzels', name: 'Pretzels', mealType: ['snack'], categories: ['vegetarian', 'quick', 'budget', 'low-effort'], ingredients: ['Pretzels'], effort: 'low', time: 1 },
  { id: 'veggie-sticks', name: 'Veggie Sticks', mealType: ['snack'], categories: ['vegan', 'vegetarian', 'healthy', 'quick', 'cold', 'budget', 'low-effort'], ingredients: ['Carrot', 'Cucumber', 'Bell Pepper'], effort: 'low', time: 5 },

  // ---------- Dessert ----------
  { id: 'ice-cream', name: 'Ice Cream', mealType: ['dessert'], categories: ['vegetarian', 'sweet', 'cold', 'quick', 'low-effort'], ingredients: ['Ice Cream'], effort: 'low', time: 2 },
  { id: 'frozen-yogurt', name: 'Frozen Yogurt', mealType: ['dessert'], categories: ['vegetarian', 'sweet', 'cold', 'healthy', 'quick', 'low-effort'], ingredients: ['Frozen Yogurt'], effort: 'low', time: 2 },
  { id: 'brownie', name: 'Brownie', mealType: ['dessert'], categories: ['vegetarian', 'sweet', 'comfort'], ingredients: ['Dark Chocolate', 'Butter', 'Eggs'], effort: 'medium', time: 35 },
  { id: 'cheesecake', name: 'Cheesecake', mealType: ['dessert'], categories: ['vegetarian', 'sweet', 'comfort'], ingredients: ['Cottage Cheese', 'Cheese', 'Butter'], effort: 'high', time: 60 },
  { id: 'chocolate-mousse', name: 'Chocolate Mousse', mealType: ['dessert'], categories: ['vegetarian', 'sweet', 'cold'], ingredients: ['Dark Chocolate', 'Eggs', 'Milk'], effort: 'medium', time: 20 },
  { id: 'fruit-salad', name: 'Fruit Salad', mealType: ['dessert', 'snack'], categories: ['vegan', 'vegetarian', 'healthy', 'cold', 'quick', 'budget', 'low-effort'], ingredients: ['Apple', 'Banana', 'Grapes', 'Orange'], effort: 'low', time: 8 },
  { id: 'rice-pudding', name: 'Rice Pudding', mealType: ['dessert'], categories: ['vegetarian', 'sweet', 'comfort'], ingredients: ['White Rice', 'Milk', 'Honey'], effort: 'medium', time: 30 },
  { id: 'banana-bread', name: 'Banana Bread', mealType: ['dessert', 'breakfast'], categories: ['vegetarian', 'sweet', 'comfort', 'meal-prep'], ingredients: ['Banana', 'Eggs', 'Butter'], effort: 'medium', time: 55 },
  { id: 'cookies', name: 'Cookies', mealType: ['dessert', 'snack'], categories: ['vegetarian', 'sweet', 'comfort', 'quick', 'low-effort'], ingredients: ['Cookies'], effort: 'low', time: 1 },

  // ---------- Drinks ----------
  { id: 'coffee', name: 'Coffee', mealType: ['drink'], categories: ['vegan', 'vegetarian', 'quick', 'hot', 'budget', 'low-effort'], ingredients: ['Coffee', 'Water'], effort: 'low', time: 3 },
  { id: 'iced-coffee', name: 'Iced Coffee', mealType: ['drink'], categories: ['vegetarian', 'quick', 'cold', 'budget', 'low-effort'], ingredients: ['Coffee', 'Milk'], effort: 'low', time: 5 },
  { id: 'tea', name: 'Tea', mealType: ['drink'], categories: ['vegan', 'vegetarian', 'quick', 'hot', 'budget', 'low-effort'], ingredients: ['Tea', 'Water'], effort: 'low', time: 3 },
  { id: 'water', name: 'Water', mealType: ['drink'], categories: ['vegan', 'vegetarian', 'healthy', 'quick', 'cold', 'budget', 'low-effort'], ingredients: ['Water'], effort: 'low', time: 1 },
  { id: 'sparkling-water', name: 'Sparkling Water', mealType: ['drink'], categories: ['vegan', 'vegetarian', 'quick', 'cold', 'budget', 'low-effort'], ingredients: ['Sparkling Water'], effort: 'low', time: 1 },
  { id: 'orange-juice', name: 'Orange Juice', mealType: ['drink'], categories: ['vegan', 'vegetarian', 'healthy', 'quick', 'cold', 'budget', 'low-effort'], ingredients: ['Orange Juice'], effort: 'low', time: 1 },
  { id: 'mango-smoothie', name: 'Mango Smoothie', mealType: ['drink', 'breakfast'], categories: ['vegan', 'vegetarian', 'healthy', 'cold', 'quick'], ingredients: ['Frozen Mango', 'Orange Juice', 'Oat Milk'], effort: 'low', time: 5 },
  { id: 'chocolate-shake', name: 'Chocolate Shake', mealType: ['drink', 'dessert'], categories: ['vegetarian', 'sweet', 'cold', 'quick'], ingredients: ['Milk', 'Dark Chocolate', 'Ice Cream'], effort: 'low', time: 5 },
  { id: 'hot-chocolate', name: 'Hot Chocolate', mealType: ['drink'], categories: ['vegetarian', 'sweet', 'hot', 'comfort', 'quick'], ingredients: ['Milk', 'Dark Chocolate'], effort: 'low', time: 8 },
  { id: 'green-smoothie', name: 'Green Smoothie', mealType: ['drink', 'breakfast'], categories: ['vegan', 'vegetarian', 'healthy', 'cold', 'quick'], ingredients: ['Spinach', 'Banana', 'Oat Milk'], effort: 'low', time: 6 },
  { id: 'lemonade', name: 'Lemonade', mealType: ['drink'], categories: ['vegan', 'vegetarian', 'quick', 'cold', 'budget'], ingredients: ['Lemon', 'Water'], effort: 'low', time: 5 },
  { id: 'milkshake', name: 'Milkshake', mealType: ['drink', 'dessert'], categories: ['vegetarian', 'sweet', 'cold', 'comfort'], ingredients: ['Milk', 'Ice Cream'], effort: 'low', time: 5 },

  // ---------- Personal favorites (smoothie bowls) ----------
  { id: 'acai-bowl', name: 'Acai Bowl', mealType: ['breakfast', 'snack'], categories: ['vegan', 'vegetarian', 'healthy', 'cold', 'sweet'], ingredients: ['Banana', 'Granola', 'Almond Milk'], effort: 'medium', time: 10 },
  { id: 'acai-protein-bowl', name: 'Acai Protein Bowl', mealType: ['breakfast', 'snack'], categories: ['vegan', 'vegetarian', 'healthy', 'high-protein', 'cold', 'sweet'], ingredients: ['Protein Shake', 'Banana', 'Granola'], effort: 'medium', time: 10 },
  { id: 'mango-smoothie-bowl', name: 'Mango Smoothie Bowl', mealType: ['breakfast', 'snack'], categories: ['vegan', 'vegetarian', 'healthy', 'cold', 'sweet'], ingredients: ['Frozen Mango', 'Banana', 'Oat Milk', 'Granola'], effort: 'medium', time: 10 },
  { id: 'chocolate-smoothie-bowl', name: 'Chocolate Smoothie Bowl', mealType: ['breakfast', 'snack', 'dessert'], categories: ['vegetarian', 'healthy', 'cold', 'sweet'], ingredients: ['Banana', 'Dark Chocolate', 'Milk', 'Granola'], effort: 'medium', time: 10 },
  { id: 'cacao-bowl', name: 'Cacao Bowl', mealType: ['breakfast', 'snack'], categories: ['vegan', 'vegetarian', 'healthy', 'cold', 'sweet'], ingredients: ['Banana', 'Dark Chocolate', 'Oat Milk', 'Granola'], effort: 'medium', time: 10 },
  { id: 'oreo-protein-bowl', name: 'Oreo Protein Bowl', mealType: ['breakfast', 'snack', 'dessert'], categories: ['vegetarian', 'high-protein', 'cold', 'sweet', 'comfort'], ingredients: ['Cookies', 'Protein Shake', 'Milk', 'Granola'], effort: 'medium', time: 10 },

  // ---------- Added for personal safe-meal seeding ----------
  { id: 'ninja-creami-chocolate', name: 'Ninja Creami Chocolate Ice Cream', mealType: ['dessert'], categories: ['vegetarian', 'sweet', 'cold', 'meal-prep'], ingredients: ['Milk', 'Protein Shake', 'Dark Chocolate'], effort: 'medium', time: 10 },
  { id: 'ninja-creami-mango', name: 'Ninja Creami Mango Ice Cream', mealType: ['dessert'], categories: ['vegan', 'vegetarian', 'healthy', 'sweet', 'cold', 'meal-prep'], ingredients: ['Frozen Mango', 'Oat Milk', 'Protein Shake'], effort: 'medium', time: 10 },
  { id: 'pizza-margherita', name: 'Pizza Margherita', mealType: ['dinner'], categories: ['vegetarian', 'comfort', 'savory'], ingredients: ['Tomato Sauce', 'Mozzarella'], effort: 'medium', time: 25 },
  { id: 'sushi-rice-bowl', name: 'Sushi Rice Bowl', mealType: ['lunch', 'dinner'], categories: ['vegan', 'vegetarian', 'healthy'], ingredients: ['Sushi Rice', 'Avocado', 'Cucumber'], effort: 'low', time: 15 },
  { id: 'crispy-tofu-bowl', name: 'Crispy Tofu Bowl', mealType: ['dinner'], categories: ['vegan', 'vegetarian', 'high-protein', 'healthy'], ingredients: ['Tofu', 'White Rice', 'Broccoli', 'Soy Sauce'], effort: 'medium', time: 25 },
  { id: 'rice-noodle-bowl', name: 'Rice Noodle Bowl', mealType: ['dinner', 'lunch'], categories: ['vegan', 'vegetarian', 'savory'], ingredients: ['Noodles', 'Carrot', 'Bell Pepper', 'Soy Sauce'], effort: 'medium', time: 20 },
  { id: 'vegetarian-gyoza-bowl', name: 'Vegetarian Gyoza Bowl', mealType: ['dinner'], categories: ['vegetarian', 'savory', 'comfort'], ingredients: ['Gyoza', 'White Rice', 'Soy Sauce'], effort: 'low', time: 15 },
  { id: 'brioche-sandwich', name: 'Brioche Sandwich', mealType: ['lunch', 'breakfast'], categories: ['vegetarian', 'comfort', 'savory'], ingredients: ['Bread', 'Cheese', 'Butter'], effort: 'low', time: 8 },
  { id: 'veggie-nuggets-fries', name: 'Veggie Nuggets & Fries', mealType: ['dinner'], categories: ['vegetarian', 'comfort', 'savory'], ingredients: ['Vegan Nuggets', 'Fries'], effort: 'low', time: 20 },
  { id: 'cheese-toast', name: 'Cheese Toast', mealType: ['breakfast', 'snack'], categories: ['vegetarian', 'comfort', 'savory', 'quick'], ingredients: ['Bread', 'Cheese'], effort: 'low', time: 6 },
  { id: 'acai-smoothie', name: 'Acai Smoothie', mealType: ['drink', 'breakfast'], categories: ['vegan', 'vegetarian', 'healthy', 'cold', 'quick'], ingredients: ['Acai', 'Almond Milk', 'Banana'], effort: 'low', time: 5 },
];
